baseURL = "https://iceberg-diary.com/"
languageCode = 'ja-jp'
title = "氷山の一角ブログ Frozen Terminal"
hasCJKLanguage = true
summaryLength = 100
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  title = "氷山の一角ブログ Frozen Terminal"
  subtitle = "Lubuntuから更新中"
  avatar = ""
  logo = ""
  favicon = "/img/favicon.ico"
  showNavbarLinks = true
  showPageDates = true
  showReadingTime = true
  showFullPostContent = false
  googleAnalytics = "G-XXXXXXXXXX"
  description = "Lubuntuの活用法やゲーム、サブカル、日日々を綴る個人ブログ。"
  customCSS = ["css/custom.css"]
  math = true
  custom_footer = "<a href='/privacy-policy/'>プライバシーポリシー</a>"
  keywords = ["Lubuntu", "Linux", "ブログ", "Frozen Terminal"]

[params.author]
  name = "深海 航"
  twitter = "https://x.com/MSgbeGGF0Q87402"
  showToc = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2

[[menu.main]]
    name = "Search"
    url = "/tags/"
    weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]